package com.github.tobi812.sprykerplugin.constants

object SprykerConstants {
    const val BUNDLE_NAME = "bundle_name"
    const val PROJECT_NAME = "project_name"
    const val CLASS_NAME = "class_name"
    const val YVES_CONTROLLER = "yves_controller"
    const val YVES_FACTORY = "yves_factory"
    const val YVES_DEPENDENCY_PROVIDER = "yves_dependency_provider"
    const val YVES_PLUGIN = "yves_plugin"
    const val ZED_CONTROLLER = "zed_controller"
    const val ZED_COMMUNICATION_FACTORY = "zed_communication_factory"
    const val ZED_BUSINESS_FACTORY = "zed_business_factory"
    const val ZED_PERSISTENCE_FACTORY = "zed_persistence_factory"
    const val ZED_FACADE = "zed_facade"
    const val ZED_QUERY_CONTAINER = "zed_query_container"
    const val ZED_CONFIG = "zed_config"
    const val ZED_DEPENDENCY_PROVIDER = "zed_dependency_provider"
    const val ZED_PLUGIN = "zed_plugin"
    const val CLIENT = "client"
    const val CLIENT_PLUGIN = "client_plugin"
    const val CLIENT_FACTORY = "client_factory"
    const val CLIENT_DEPENDENCY_PROVIDER = "client_dependency_provider"
    const val BUNDLE_NAME_PLACEHOLDER = "{{ bundleName }}"
    const val PROJECT_NAME_PLACEHOLDER = "{{ projectName }}"
    const val CLASS_NAME_PLACEHOLDER = "{{ className }}"
}